@extends('layouts.frontend')
@section('content')

<div class="row">
    <div class="col-12">
        <div class="widget-content widget-content-area br-8 mb-4">
            <div class="calendar-header d-flex justify-content-between align-items-center mb-4">
                <h4 class="mb-0">Academic Calendar</h4>
                <a href="{{ route('absensi.academic-calendar.index') }}" class="btn btn-primary btn-sm">
                    Manage Calendar
                </a>
            </div>
            
            <div class="calendar-wrapper">
                <!-- Month Navigation -->
                <div class="calendar-nav d-flex justify-content-between align-items-center mb-4">
                    <button class="btn btn-outline-secondary btn-sm" id="prevMonth">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="15 18 9 12 15 6"></polyline></svg>
                    </button>
                    <h5 id="currentMonth" class="mb-0"></h5>
                    <button class="btn btn-outline-secondary btn-sm" id="nextMonth">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="9 18 15 12 9 6"></polyline></svg>
                    </button>
                </div>
                
                <!-- Calendar Grid -->
                <div class="calendar-grid">
                    <div class="calendar-weekdays">
                        <div class="text-center">Sun</div>
                        <div class="text-center">Mon</div>
                        <div class="text-center">Tue</div>
                        <div class="text-center">Wed</div>
                        <div class="text-center">Thu</div>
                        <div class="text-center">Fri</div>
                        <div class="text-center">Sat</div>
                    </div>
                    <div class="calendar-days" id="calendarDays">
                        <!-- Days will be generated by JavaScript -->
                    </div>
                </div>
            </div>
            
            <!-- Legend -->
            <div class="calendar-legend mt-4">
                <div class="d-flex flex-wrap gap-3">
                    <div class="d-flex align-items-center">
                        <span class="badge bg-success me-2">&nbsp;</span>
                        <small>Holiday</small>
                    </div>
                    <div class="d-flex align-items-center">
                        <span class="badge bg-danger me-2">&nbsp;</span>
                        <small>Exam</small>
                    </div>
                    <div class="d-flex align-items-center">
                        <span class="badge bg-primary me-2">&nbsp;</span>
                        <small>Semester</small>
                    </div>
                    <div class="d-flex align-items-center">
                        <span class="badge bg-warning me-2">&nbsp;</span>
                        <small>Event</small>
                    </div>
                    <div class="d-flex align-items-center">
                        <span class="badge bg-secondary me-2">&nbsp;</span>
                        <small>Other</small>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
.calendar-grid {
    border: 1px solid #e0e0e0;
    border-radius: 8px;
    overflow: hidden;
}

.calendar-weekdays {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
    background: #f8f9fa;
    border-bottom: 1px solid #e0e0e0;
}

.calendar-weekdays > div {
    padding: 10px;
    text-align: center;
    font-weight: 600;
    font-size: 12px;
    color: #6c757d;
}

.calendar-days {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
}

.calendar-day {
    min-height: 80px;
    padding: 8px;
    border-right: 1px solid #e0e0e0;
    border-bottom: 1px solid #e0e0e0;
    background: #fff;
}

.calendar-day:nth-child(7n) {
    border-right: none;
}

.calendar-day.other-month {
    background: #f8f9fa;
    color: #adb5bd;
}

.calendar-day.today {
    background: #e7f5ff;
}

.day-number {
    font-weight: 600;
    font-size: 14px;
    margin-bottom: 5px;
}

.event-item {
    font-size: 10px;
    padding: 2px 5px;
    margin-bottom: 2px;
    border-radius: 3px;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}

.event-item.holiday {
    background: #d1fae5;
    color: #065f46;
}

.event-item.exam {
    background: #fee2e2;
    color: #991b1b;
}

.event-item.semester {
    background: #dbeafe;
    color: #1e40af;
}

.event-item.event {
    background: #fef3c7;
    color: #92400e;
}

.event-item.other {
    background: #e5e7eb;
    color: #374151;
}

.badge {
    display: inline-block;
    width: 12px;
    height: 12px;
    border-radius: 2px;
}
</style>

<script>
document.addEventListener('DOMContentLoaded', function() {
    let currentDate = new Date();
    const calendars = @json($calendars);
    
    function renderCalendar() {
        const year = currentDate.getFullYear();
        const month = currentDate.getMonth();
        
        document.getElementById('currentMonth').textContent = 
            new Date(year, month).toLocaleDateString('en-US', { month: 'long', year: 'numeric' });
        
        const firstDay = new Date(year, month, 1);
        const lastDay = new Date(year, month + 1, 0);
        const startDay = firstDay.getDay();
        const totalDays = lastDay.getDate();
        
        const daysContainer = document.getElementById('calendarDays');
        daysContainer.innerHTML = '';
        
        // Previous month days
        const prevMonthLastDay = new Date(year, month, 0).getDate();
        for (let i = startDay - 1; i >= 0; i--) {
            const dayDiv = document.createElement('div');
            dayDiv.className = 'calendar-day other-month';
            dayDiv.innerHTML = `<span class="day-number">${prevMonthLastDay - i}</span>`;
            daysContainer.appendChild(dayDiv);
        }
        
        // Current month days
        const today = new Date();
        for (let i = 1; i <= totalDays; i++) {
            const dayDiv = document.createElement('div');
            dayDiv.className = 'calendar-day';
            
            if (today.getDate() === i && today.getMonth() === month && today.getFullYear() === year) {
                dayDiv.classList.add('today');
            }
            
            dayDiv.innerHTML = `<span class="day-number">${i}</span>`;
            
            // Add events for this day
            const currentDayStr = `${year}-${String(month + 1).padStart(2, '0')}-${String(i).padStart(2, '0')}`;
            
            calendars.forEach(calendar => {
                const startDate = calendar.start_date;
                const endDate = calendar.end_date;
                
                if (currentDayStr >= startDate && currentDayStr <= endDate) {
                    const eventDiv = document.createElement('div');
                    eventDiv.className = `event-item ${calendar.event_type}`;
                    eventDiv.textContent = calendar.title;
                    eventDiv.title = calendar.title + '\n' + 
                        new Date(startDate).toLocaleDateString() + ' - ' + new Date(endDate).toLocaleDateString();
                    dayDiv.appendChild(eventDiv);
                }
            });
            
            daysContainer.appendChild(dayDiv);
        }
        
        // Next month days
        const remainingDays = 42 - (startDay + totalDays);
        for (let i = 1; i <= remainingDays; i++) {
            const dayDiv = document.createElement('div');
            dayDiv.className = 'calendar-day other-month';
            dayDiv.innerHTML = `<span class="day-number">${i}</span>`;
            daysContainer.appendChild(dayDiv);
        }
    }
    
    document.getElementById('prevMonth').addEventListener('click', function() {
        currentDate.setMonth(currentDate.getMonth() - 1);
        renderCalendar();
    });
    
    document.getElementById('nextMonth').addEventListener('click', function() {
        currentDate.setMonth(currentDate.getMonth() + 1);
        renderCalendar();
    });
    
    renderCalendar();
});
</script>

@endsection
