@extends('layouts.frontend')
@section('content')

{{--
    FIX (14 September 2026, permintaan user -- "dashboard itu hanya tanggal
    saja"): widget "My University Applications" + alur Register manual yang
    sempat ditaruh di halaman ini SUDAH DIPINDAH ke halaman terpisah
    "InaStudy" (resources/views/student-portal/inastudy/index.blade.php),
    dituju langsung lewat menu "InaStudy" di sidebar. Halaman ini sekarang
    murni cuma Academic Calendar.
--}}

<div class="row">
    <div class="col-12">
        <div class="widget-content widget-content-area br-8 mb-4">
            <div class="calendar-header d-flex justify-content-between align-items-center mb-4">
                <h4 class="mb-0">Academic Calendar</h4>
                <a href="{{ route('absensi.academic-calendar.index') }}" class="btn btn-primary btn-sm">
                    Manage Calendar
                </a>
            </div>
            
            <div class="calendar-wrapper">
                <!-- Month Navigation -->
                <div class="calendar-nav d-flex justify-content-between align-items-center mb-4">
                    <button class="btn btn-outline-secondary btn-sm" id="prevMonth">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="15 18 9 12 15 6"></polyline></svg>
                    </button>
                    <h5 id="currentMonth" class="mb-0"></h5>
                    <button class="btn btn-outline-secondary btn-sm" id="nextMonth">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="9 18 15 12 9 6"></polyline></svg>
                    </button>
                </div>
                
                {{-- FIX (15 September 2026, permintaan user -- "tampilan di
                     smartphone itu berantakan dan numpuk"): grid kalender
                     (7 kolom) dibungkus wrapper yang bisa di-scroll
                     horizontal SENDIRI (bukan seluruh halaman) di layar
                     sempit -- .calendar-grid dikasih min-width lewat CSS di
                     bawah, jadi kalau layarnya lebih sempit dari itu,
                     tinggal geser kalendernya, bukan tiap kotak hari jadi
                     kegencet/numpuk teksnya. --}}
                <div class="calendar-scroll">
                    <!-- Calendar Grid -->
                    <div class="calendar-grid">
                        <div class="calendar-weekdays">
                            <div class="text-center">Sun</div>
                            <div class="text-center">Mon</div>
                            <div class="text-center">Tue</div>
                            <div class="text-center">Wed</div>
                            <div class="text-center">Thu</div>
                            <div class="text-center">Fri</div>
                            <div class="text-center">Sat</div>
                        </div>
                        <div class="calendar-days" id="calendarDays">
                            <!-- Days will be generated by JavaScript -->
                        </div>
                    </div>
                </div>
            </div>
            
            <!-- Legend -->
            <div class="calendar-legend mt-4">
                <div class="d-flex flex-wrap gap-3">
                    <div class="d-flex align-items-center">
                        <span class="badge bg-success me-2">&nbsp;</span>
                        <small>Holiday</small>
                    </div>
                    <div class="d-flex align-items-center">
                        <span class="badge bg-danger me-2">&nbsp;</span>
                        <small>Exam</small>
                    </div>
                    <div class="d-flex align-items-center">
                        <span class="badge bg-primary me-2">&nbsp;</span>
                        <small>Semester</small>
                    </div>
                    <div class="d-flex align-items-center">
                        <span class="badge bg-warning me-2">&nbsp;</span>
                        <small>Event</small>
                    </div>
                    <div class="d-flex align-items-center">
                        <span class="badge bg-secondary me-2">&nbsp;</span>
                        <small>Other</small>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
.calendar-grid {
    border: 1px solid #e0e0e0;
    border-radius: 8px;
    overflow: hidden;
}

.calendar-weekdays {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
    background: #f8f9fa;
    border-bottom: 1px solid #e0e0e0;
}

.calendar-weekdays > div {
    padding: 10px;
    text-align: center;
    font-weight: 600;
    font-size: 12px;
    color: #6c757d;
}

.calendar-days {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
}

.calendar-day {
    min-height: 80px;
    padding: 8px;
    border-right: 1px solid #e0e0e0;
    border-bottom: 1px solid #e0e0e0;
    background: #fff;
}

.calendar-day:nth-child(7n) {
    border-right: none;
}

.calendar-day.other-month {
    background: #f8f9fa;
    color: #adb5bd;
}

.calendar-day.today {
    background: #e7f5ff;
}

.day-number {
    font-weight: 600;
    font-size: 14px;
    margin-bottom: 5px;
}

.event-item {
    font-size: 10px;
    padding: 2px 5px;
    margin-bottom: 2px;
    border-radius: 3px;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}

.event-item.holiday {
    background: #d1fae5;
    color: #065f46;
}

.event-item.exam {
    background: #fee2e2;
    color: #991b1b;
}

.event-item.semester {
    background: #dbeafe;
    color: #1e40af;
}

.event-item.event {
    background: #fef3c7;
    color: #92400e;
}

.event-item.other {
    background: #e5e7eb;
    color: #374151;
}

/*
 * SEBELUMNYA: selector ".badge" polos di sini (dimaksudkan cuma untuk kotak
 * kecil warna di Legend kalender) menimpa class Bootstrap ".badge" di
 * SELURUH halaman ini -- termasuk badge status "Submitted"/dst di tabel "My
 * University Applications" di atas, yang jadi keciiil banget (12x12px)
 * sampai teksnya tidak kelihatan sama sekali (cuma tampil kotak polos).
 * Diperbaiki dengan scope selector ke ".calendar-legend .badge" saja, supaya
 * cuma kotak warna Legend yang kena, badge Bootstrap lain di halaman ini
 * tetap tampil normal (lihat pertanyaan user "itu status kotak gitu aja
 * mksdnya apa ya", 10 September 2026).
 */
.calendar-legend .badge {
    display: inline-block;
    width: 12px;
    height: 12px;
    border-radius: 2px;
}

/*
 * FIX (15 September 2026, permintaan user -- "perbaiki tampilan responsive
 * nya ketika buka di handphone", "tampilan di smartphone itu berantakan dan
 * numpuk"): sebelumnya grid kalender (7 kolom, .calendar-day min-height 80px)
 * ikut menyempit mengikuti lebar layar HP -- di layar sekitar 360-400px tiap
 * kotak hari cuma kebagian ~45-50px, jadi angka tanggal + event-item saling
 * numpuk/kepotong. Sekarang .calendar-grid dikasih min-width (dibungkus
 * .calendar-scroll yang overflow-x:auto) supaya kotak hari TETAP proporsional
 * dan tinggal digeser horizontal di HP, BUKAN dipaksa menyempit sampai tidak
 * kebaca -- ini SATU-SATUNYA elemen yang boleh scroll ke samping, halaman
 * dashboard sendiri tetap tidak ikut geser horizontal.
 */
.calendar-scroll {
    overflow-x: auto;
    -webkit-overflow-scrolling: touch;
}

.calendar-grid {
    min-width: 480px;
}

@media (max-width: 576px) {
    .calendar-header {
        flex-wrap: wrap;
        gap: 10px;
    }

    .calendar-header .btn {
        width: 100%;
    }

    .calendar-nav h5 {
        font-size: 15px;
    }

    .calendar-legend {
        gap: 8px !important;
    }

    .calendar-legend small {
        font-size: 11px;
    }
}
</style>

<script>
document.addEventListener('DOMContentLoaded', function() {
    let currentDate = new Date();
    const calendars = @json($calendars);
    
    function renderCalendar() {
        const year = currentDate.getFullYear();
        const month = currentDate.getMonth();
        
        document.getElementById('currentMonth').textContent = 
            new Date(year, month).toLocaleDateString('en-US', { month: 'long', year: 'numeric' });
        
        const firstDay = new Date(year, month, 1);
        const lastDay = new Date(year, month + 1, 0);
        const startDay = firstDay.getDay();
        const totalDays = lastDay.getDate();
        
        const daysContainer = document.getElementById('calendarDays');
        daysContainer.innerHTML = '';
        
        // Previous month days
        const prevMonthLastDay = new Date(year, month, 0).getDate();
        for (let i = startDay - 1; i >= 0; i--) {
            const dayDiv = document.createElement('div');
            dayDiv.className = 'calendar-day other-month';
            dayDiv.innerHTML = `<span class="day-number">${prevMonthLastDay - i}</span>`;
            daysContainer.appendChild(dayDiv);
        }
        
        // Current month days
        const today = new Date();
        for (let i = 1; i <= totalDays; i++) {
            const dayDiv = document.createElement('div');
            dayDiv.className = 'calendar-day';
            
            if (today.getDate() === i && today.getMonth() === month && today.getFullYear() === year) {
                dayDiv.classList.add('today');
            }
            
            dayDiv.innerHTML = `<span class="day-number">${i}</span>`;
            
            // Add events for this day
            const currentDayStr = `${year}-${String(month + 1).padStart(2, '0')}-${String(i).padStart(2, '0')}`;
            
            calendars.forEach(calendar => {
                const startDate = calendar.start_date;
                const endDate = calendar.end_date;
                
                if (currentDayStr >= startDate && currentDayStr <= endDate) {
                    const eventDiv = document.createElement('div');
                    eventDiv.className = `event-item ${calendar.event_type}`;
                    eventDiv.textContent = calendar.title;
                    eventDiv.title = calendar.title + '\n' + 
                        new Date(startDate).toLocaleDateString() + ' - ' + new Date(endDate).toLocaleDateString();
                    dayDiv.appendChild(eventDiv);
                }
            });
            
            daysContainer.appendChild(dayDiv);
        }
        
        // Next month days
        const remainingDays = 42 - (startDay + totalDays);
        for (let i = 1; i <= remainingDays; i++) {
            const dayDiv = document.createElement('div');
            dayDiv.className = 'calendar-day other-month';
            dayDiv.innerHTML = `<span class="day-number">${i}</span>`;
            daysContainer.appendChild(dayDiv);
        }
    }
    
    document.getElementById('prevMonth').addEventListener('click', function() {
        currentDate.setMonth(currentDate.getMonth() - 1);
        renderCalendar();
    });
    
    document.getElementById('nextMonth').addEventListener('click', function() {
        currentDate.setMonth(currentDate.getMonth() + 1);
        renderCalendar();
    });
    
    renderCalendar();
});
</script>

@endsection
